#!/bin/bash
suspendsystem(){
    systemctl suspend
}

hidden(){ # list only dotfiles and pass args to ls
    ls -a "$@" | grep '^\.' ; 
}

#TODO Make of this one liner a function
#find DCIM/ -maxdepth 1 -type f -print0 | xargs -0 shuf -e -n 10 -z | xargs -0 cp -vt atest.d/

cprand(){ # cp x rand FILES to target

    find "$1" -type f -print0 | xargs -0 shuf -e -n "$3" -z | xargs -0 cp -vt "$2"
}
