#!/bin/bash
# bash_aliases
#
# TODO group vXxxx aliases

alias reload='. $HOME/.bashrc'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'
alias cdhist="dirs -v"

alias cl='clear'
alias cla='clear;la'
alias cll='clear;ll'
alias cls='clear;ls'
alias clal='clear;lal'
alias rmi='rm -i'
alias rmdir='rm -rfI'
alias d='date +%Y%m%d-%H%M%S'
alias h='history'
alias ls='ls -F --color=auto'
alias l='ls'
alias la='ls -ah'
alias ll='ls -lh'
alias llt='ls -lhrt'
alias lu='ls -lturh'
alias lal='ls -alh'
alias lalt='ls -alhrt'
alias ldir='ll -d */'
alias sl='ls'
alias less='less -iMFR'
alias more='less'
alias mroe='more'
alias r='fc -s'
alias igrep='grep -i'
alias rgrep='grep -r'
alias ftail='tail -f'
alias hn='hostname -a'
alias va='vim ~/.dotfiles/aliases; source ~/.dotfiles/aliases && echo "aliases sourced"'
alias ca='va'
alias aliases='less ~/.dotfiles/aliases'
alias vf='vim ~/.dotfiles/functions.d/functions_walo ; reload && echo "functions sourced"'
alias vfs='vim ~/.dotfiles/functions.d/functions_sharfah ; reload && echo "functions sourced"'
alias vsources='sudo vim /etc/apt/sources.list'
alias vi='vim'
alias cim='vim'
alias vin='vim'
alias mc='mv'
alias mount='sudo mount'
alias umount='sudo umount'

# coloured output using grc
alias ping='grc ping'
#alias netstat='grc netstat'
alias diff='grc diff'
alias tail='grc tail'
alias ps='grc ps'
alias lsof='grc lsof'

#alias scp='scp -o StrictHostKeyChecking=no -c arcfour -o Compression=no'
alias fullps='ps -auxwww'
alias functions='declare -F'
alias xml='xmllint --format'


# Walo aliases
# variables
today=$(date +%d%m%Y)
alias time="date +%H%M%S"


# apps GUI
alias chrome='google-chrome &'
#in script named inbox
alias apex='google-chrome https://apex.prosperousuniverse.com/ && https://docs.google.com/spreadsheets/d/1UAWZxE9mie8xeoOPeQ7S-Y4Cu6qk2l5WOfzIoDmkL_Q/edit# &'
alias inbox='/usr/local/bin/openinboxes &'
alias o='okular'
alias lindo='lindo_mdp_halavus'
alias workers='steam steam://rungameid/784150 & reniceworkers'

# Workers & Ressources
alias reniceworkers='sudo renice -n -20 -p $(pgrep SOVIET32.exe) ; sudo renice -n -20 -p $(pgrep wineserver)'
alias reniceearthx='sudo renice -n -20 -p $(pgrep earthx.x86_64)'
# DF
alias dfvanilla='~/games/current/df'
alias dfhack='~/games/current/dfhack'
alias cddf='pushd ~/games/current && clal'
alias cdinit='pushd ~/games/current/data/init && clal'
alias renicedf='sudo renice -n -20 -p $(pgrep Dwarf_Fortress)'

# moving
alias p=pushd
alias pp=popd
alias code='cd /home/walo/code_the_web'
alias pbin="p /usr/local/bin/"
alias psbin="p /usr/local/sbin/"
alias dot='p ~/.dotfiles'
alias cdprun='p /home/walo/code_the_web/flask-python/PrUn_inventory_importer/inventory_importer ; lal'
alias cdship='p /home/walo/code_the_web/python/PrUn/shipping_profits ; lal'


# editing/updating
alias edgrubmenu='sudo grub-customizer'
alias update-grub='sudo update-grub'
alias vsmb='sudo vim /etc/samba/smb.conf && sudo systemctl restart smbd'

# commands
#  Python, Virtualenv, Flask related
alias pi='py -i'
alias rmpyc='find . -name "*.pyc" -delete'
alias avenv='source venv/bin/activate'
alias py='py3'
alias py3='python3'
alias startimporter_localhost='/home/walo/code_the_web/flask-python/PrUn_inventory_importer/inventory_importer/venv/bin/gunicorn -b 0.0.0.0:5000 wsgi:app'

#  System
alias aptiup='echo "update" && aptitude update && echo "full-upgrade" && aptitude full-upgrade && echo "apt-file upgrade" && sudo apt-file update && echo "autoclean" && aptitude autoclean && echo "" && echo "purge" && aptitude purge'
alias aptitude='sudo aptitude'
alias install='aptitude install'
#alias apt-get="printf '\nUsing aptitude instead of apt.\n' && aptitude"
alias blkid='sudo blkid'
alias gparted='sudo gparted'
alias rsync='rsync -ahvPHXS --log-file=rsynclog.$today.$(time)'
#alias rsyncosx='sudo rsync -hvPSr --exclude-from=/home/walo/exclude-list'
alias vback='sudo vim /usr/local/sbin/backup'
alias readlog='less /var/log/rsnapshot.log'
alias vexclude='sudo vim /usr/local/sbin/exclude-list.txt'
alias snap='rsnapshot'
alias snyp='snap'
alias s='snap'
alias vsnap='sudo vim /etc/rsnapshot.conf'
alias backup='sudo mount /rsnapshot/ ; sudo rsnapshot sync && sudo rsnapshot alpha ; sudo umount /rsnapshot'
alias rm='rm -v'
alias mv='mv -v'
alias cp='cp -v'
#  !! In Order to have sudo work with all user aliases !!
alias sudo='sudo '
# from trash-cli pkg. See man trash for more infos.
## to restore a file sent to trash, run: restore-trash (from trash-cli pkg)
alias trash='trash-put -v'
alias trahs='trash'
alias shutdown='sudo shutdown'
alias unpack='extract'
alias c="calc"
alias du='du -sh' # Disk Usage Summary Human readable
alias m='sudo mounteddevices'
alias vfstab='sudo cp /etc/fstab /etc/fstab.$today.$(time) && sudo vim /etc/fstab'


# SSH


# git
alias vga='vim ~/.dotfiles/gitconfig'
alias status='git status'
alias addall='git add -A'
alias commit='git commit'
alias branch='git branch'
alias tree='git show-branch' # Shows the whole tree


# unordered
#alias startxampp='(cd /opt/lampp/ && sudo ./xampp start)'
alias goodnight='sudo goodnight'
alias findwalo='find . -maxdepth 1 -user walo'
alias audiveris="cd /shared/audiveris/ && gradle run"
pics="/shared/Pictures/SD_Valentin"
alias pics=$pics
alias ppics="cd $pics"
alias vex="vim ~/exclude-list"
alias ever="google-chrome https://www.evernote.com/Home.action?login=true &"
alias sortmypics="sortpics /shared/Pictures/SD_Valentin/DCIM /shared/Pictures/SD_Valentin/sorted"
